sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t upatisariputa/docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true upatisariputa/docker-app npm run test -- --coverage

after_success:
  - echo "Test success"  
